name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate plot
      run: |
        python -m src.plot

    - name: Upload plot as artifact
      uses: actions/upload-artifact@v4
      with:
        name: plot
        path: artifacts/plot.png
        retention-days: 30

    - name: Run tests
      run: |
        pytest tests/ --cov=src
